runtime: nodejs16 # or another supported version

instance_class: F2


handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /assets
  static_dir: dist/assets
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  secure: optional
  script: auto
